modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/3arthqu4ke/phobot"
license = "MIT"

[[mods]]
modId = "phobot"
version = "${version}"
displayName = "Phobot"
authors = "3arthqu4ke"
description = "A CrystalPvP plugin for PingBypass"

[[dependencies.phobot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.phobot]]
modId = "pingbypass"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"
