name: Build with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

      - name: Add build summary
        run: |
          echo "## ✅ Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- JDK Version: 17" >> $GITHUB_STEP_SUMMARY
          echo "- Gradle Build: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Artifact: [Download JAR](./artifact/app-jar)" >> $GITHUB_STEP_SUMMARY
